subject_id: "386"
root_data_dir: data/zju_lightstage/${subject_id}
smplx_dir: data/smplx

image_height: 1024
image_width: 1024

module_name: cond_model

model:
  class_name: dva.${module_name}.BodyDecoder
  n_prims: 4096
  prim_size: 16
  n_pose_dims: 84
  n_pose_enc_channels: 64
  prim_motion_enabled: True
  prim_motion_start_train: 500
  smplx_gender: male
  image_height: ${image_height}
  image_width: ${image_width}

rm:
  volradius: 10000.0
  dt: 1.0

optimizer:
  class_name: torch.optim.Adam
  lr: 0.001

loss:
  class_name: dva.losses.TotalMVPLoss
  weights:
    rgb_mse: 1.0
    mask_mae: 0.01
    prim_vol_sum: 0.001
    alpha_prior: 1.0
    vgg: 1.0

train:
  batch_size: 4
  n_epochs: 10000
  n_max_iters: 1000000
  log_every_n_steps: 10
  summary_every_n_steps: 100
  ckpt_every_n_steps: 5000
  gradient_clip_value: 5.0

cameras_train:
  [
    "01",
    "02",
    "03",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
  ]

cameras_cond: ["01", "08", "16", "21"]

tag: ${module_name}_mvp
output_dir: ${root_data_dir}/training-logs/${tag}

ref_frame: 0

data:
  image: ${root_data_dir}/videos/{camera}/{frame:06d}.png
  image_mask: ${root_data_dir}/mask_cihp/{camera}/{frame:06d}.png
  image_part_mask: ${root_data_dir}/mask_cihp/{camera}/{frame:06d}.png
  # zju_lightstage/smplx_male/${subject_id}/{frame:06d}.json
  smplx_poses: ${root_data_dir}/smplx_refitting/{frame:06d}.json
  frame_list: ${root_data_dir}/splits/all.list
  intrinsics: ${root_data_dir}/intri.yml
  extrinsics: ${root_data_dir}/extri.yml
  smplx_topology: ${smplx_dir}/SMPLX_MALE.npz
